export enum ApiErrorCode {
  // Generic
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID = 'INVALID',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DB_UNAVAILABLE = 'DB_UNAVAILABLE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_REFRESH_TOKEN = 'AUTH_MISSING_REFRESH_TOKEN',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  STUDENT_NOT_FOUND = 'STUDENT_NOT_FOUND',
  TEACHER_NOT_FOUND = 'TEACHER_NOT_FOUND',
  STUDENT_INACTIVE_OR_NOT_FOUND = 'STUDENT_INACTIVE_OR_NOT_FOUND',
  TEACHER_INACTIVE_OR_NOT_FOUND = 'TEACHER_INACTIVE_OR_NOT_FOUND',

  // Subjects / Policies
  SUBJECT_CONFLICT = 'SUBJECT_CONFLICT',
  SUBJECT_INVALID_INPUT = 'SUBJECT_INVALID_INPUT',
  POLICY_INVALID_LEVEL = 'POLICY_INVALID_LEVEL',
  POLICY_INVALID_MONTHLY_AUTO_APPROVE = 'POLICY_INVALID_MONTHLY_AUTO_APPROVE',
  POLICY_INVALID_EXPIRE_HOURS = 'POLICY_INVALID_EXPIRE_HOURS',

  // Appointments
  APPOINTMENT_STATE_CONFLICT = 'APPOINTMENT_STATE_CONFLICT',
  APPOINTMENT_REJECT_REASON_REQUIRED = 'APPOINTMENT_REJECT_REASON_REQUIRED',
  SLOT_TAKEN = 'SLOT_TAKEN',
  MAX_DAILY_REACHED = 'MAX_DAILY_REACHED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  SUBJECT_MISMATCH = 'SUBJECT_MISMATCH',

  // Availability & Blocked Times
  AVAILABILITY_INVALID_MODE = 'AVAILABILITY_INVALID_MODE',
  AVAILABILITY_CONFLICT_APPOINTMENT = 'AVAILABILITY_CONFLICT_APPOINTMENT',
  AVAILABILITY_CONFLICT_GENERAL = 'AVAILABILITY_CONFLICT_GENERAL',
  BLOCKEDTIME_CONFLICT_APPOINTMENT = 'BLOCKEDTIME_CONFLICT_APPOINTMENT',

  // Waitlist
  WAITLIST_DUPLICATE_ENTRY = 'WAITLIST_DUPLICATE_ENTRY',
  WAITLIST_ENTRY_NOT_FOUND = 'WAITLIST_ENTRY_NOT_FOUND',
  WAITLIST_FORBIDDEN_REMOVE = 'WAITLIST_FORBIDDEN_REMOVE',
  WAITLIST_SLOT_UNAVAILABLE = 'WAITLIST_SLOT_UNAVAILABLE',
  WAITLIST_EMPTY = 'WAITLIST_EMPTY',
  WAITLIST_MISSING_FIELDS = 'WAITLIST_MISSING_FIELDS',
  WAITLIST_PROMOTE_MISSING_FIELDS = 'WAITLIST_PROMOTE_MISSING_FIELDS',

  // Email/SMTP
  SMTP_CONNECTION_FAILED = 'SMTP_CONNECTION_FAILED',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  EMAIL_TEST_FAILED = 'EMAIL_TEST_FAILED',

  // Jobs
  JOB_INVALID_OFFSET = 'JOB_INVALID_OFFSET',
}

export type ApiErrorCodeType = `${ApiErrorCode}`
