import type { Metadata } from 'next'
import './globals.css'
import AuthListener from '@/components/shared/AuthListener'
import StyledComponentsRegistry from '@/components/shared/StyledComponentsRegistry'
import RouteProgress from '@/components/shared/RouteProgress'
import SentryInit from '@/components/shared/SentryInit'
import WebVitalsReporter from '@/components/shared/WebVitalsReporter'
import AuthProvider from '@/components/shared/AuthProvider'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/next'

export const metadata: Metadata = {
  title: '教育会议调度系统',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh">
      <body className="antialiased">
        <StyledComponentsRegistry>
          <SentryInit />
          <WebVitalsReporter />
          <SpeedInsights />
          <Analytics />
          <RouteProgress />
          <AuthProvider>
            <AuthListener>{children}</AuthListener>
          </AuthProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
