import type { Metadata } from 'next'
import './globals.css'
import AuthListener from '@/components/shared/AuthListener'
import StyledComponentsRegistry from '@/components/shared/StyledComponentsRegistry'
import RouteProgress from '@/components/shared/RouteProgress'

export const metadata: Metadata = {
  title: '教育会议调度系统',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh">
      <body className="antialiased">
        <StyledComponentsRegistry>
          <RouteProgress />
          <AuthListener>{children}</AuthListener>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
