name: CI + Staging Pipeline

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - run: pnpm i --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test --if-present
      - run: pnpm build

  migrate-staging:
    name: DB Migrate (staging on develop)
    runs-on: ubuntu-latest
    needs: checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm i --frozen-lockfile
      - run: pnpm db:generate
      - name: Prisma migrate deploy (staging)
        env:
          DATABASE_URL: ${{ secrets.NEON_STAGING_URL }}
        run: pnpm db:migrate:deploy

  deploy-staging:
    name: Deploy Staging (develop branch)
    runs-on: ubuntu-latest
    needs: migrate-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    permissions:
      deployments: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Deploy to Vercel (Preview)
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Wait staging up
        run: |
          echo "Staging URL: https://${{ steps.vercel.outputs.preview-url }}"
          npx wait-on --timeout 120000 https://${{ steps.vercel.outputs.preview-url }}

      - name: Run smoke tests against staging (if present)
        env:
          BASE_URL: https://${{ steps.vercel.outputs.preview-url }}
          DATABASE_URL: ${{ secrets.NEON_STAGING_URL }}
        run: |
          pnpm i --frozen-lockfile
          pnpm run --if-present smoke
