name: Release to Production

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  release:
    name: Migrate DB and Deploy (prod)
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm i --frozen-lockfile
      - run: pnpm db:generate

      - name: Prisma migrate deploy (prod)
        env:
          DATABASE_URL: ${{ secrets.NEON_PROD_URL }}
        run: pnpm db:migrate:deploy

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
