name: Secrets Sanity Check

on:
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      S_VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      S_VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      S_VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      S_NEON_STAGING_URL: ${{ secrets.NEON_STAGING_URL }}
      S_NEON_PROD_URL: ${{ secrets.NEON_PROD_URL }}
    steps:
      - name: Verify required GitHub Actions secrets are set
        run: |
          missing=0
          check() { var="$1"; name="$2"; if [ -z "$var" ]; then echo "❌ Missing secret: $name"; missing=1; else echo "✅ $name is set"; fi }
          check "$S_VERCEL_TOKEN" VERCEL_TOKEN
          check "$S_VERCEL_ORG_ID" VERCEL_ORG_ID
          check "$S_VERCEL_PROJECT_ID" VERCEL_PROJECT_ID
          check "$S_NEON_STAGING_URL" NEON_STAGING_URL
          check "$S_NEON_PROD_URL" NEON_PROD_URL
          if [ "$missing" -ne 0 ]; then
            echo "\nOne or more required secrets are missing. Add them under Settings → Secrets and variables → Actions."
            exit 1
          fi
          echo "\nAll required secrets are present."
